### ISSUE TITLE
hyper-core custom-entity-bukkit-1.0.jar 또는 custom-entity-bukkit-1.0.pom문의

### ISSUE THREAD

**Issue by jini5012** [patrick-mc/hyper-core-game#2]
제가 hyper core 빌드를 할때 noonmaru님의 customentity는 jar밖에 없는데 자꾸 pom이 있어야 된다고
해가지고 pom을 어떻게 만들어야 될지 모르겠어요

오류로그* What went wrong:
Execution failed for task ':v1_12_R1:compileKotlin'.
> Could not resolve all files for configuration ':v1_12_R1:compileClasspath'.
   > Could not find com.github.noonmaru:custom-entity-bukkit:1.0.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/com/github/noonmaru/custom-entity-bukkit/1.0/custom-entity-bukkit-1.0.pom
       - https://dl.bintray.com/kotlin/dokka/com/github/noonmaru/custom-entity-bukkit/1.0/custom-entity-bukkit-1.0.pom
       - https://oss.sonatype.org/content/repositories/snapshots/com/github/noonmaru/custom-entity-bukkit/1.0/custom-entity-bukkit-1.0.pom
       - https://hub.spigotmc.org/nexus/content/repositories/snapshots/com/github/noonmaru/custom-entity-bukkit/1.0/custom-entity-bukkit-1.0.pom
       - file:/C:/Users/진이/.m2/repository/com/github/noonmaru/custom-entity-bukkit/1.0/custom-entity-bukkit-1.0.pom
     Required by:
         project :v1_12_R1

**Comment by jini5012** [comment]
도와주세요ㅠㅠㅠㅠ

**Comment by patrick-mc** [comment]
제가 dependency를 바꾸고 방치해뒀네요 ;;
수정 후 커밋하겠습니다

**Comment by patrick-mc** [comment]
해결되었습니다. 확인 부탁드립니다.
