### ISSUE TITLE
Custom-entity-mod문의

### ISSUE THREAD

**Issue by devil0414** [patrick-mc/hyper-core-game#4]
이 플러그인을 쓰기 위해서는 tap, custom-entity-bukkit, Custom-entity-mod가 필요한 것으로 압니다. Tap, custom-entity-bukkit은 noonmaru님의github에서 받았고 custom-entity-mod가 필요합니다. 그러나 noonmaru님의 github에는 모드가 없어서 하이퍼코어를 플레이할 수가 없습니다. 그래서 custom-entity-mod를 github에 올려주시면 좋겠습니다.

**Comment by devil0414** [comment]
그런데 옛날에 custom-entity-forge를 가지고 계시지 않았나요? 그거라도 올려주시면 안될까요?

**Comment by patrick-mc** [comment]
결론부터 말씀드리자면, 지훤 계획 없습니다.

<details>
올해 6월 초 사용중이던 노트북이 의도치 않게 초기화되면서 개발중이던 프로젝트와, 빌드해둔 프로젝트와 클라이언트, 서버 모두 날아가게 되었습니다. 그 때 이후로 레거시 버전 (1.13.2 이전) 개발을 거의 하지 않고, 유지 보수도 거의 하지 않게 되었습니다. 현재는 1.16 최신 버전의 bukkit 플러그인만 개발 중이며, 이전 버전을 타겟으로 한 플러그인들을 관리하지 않을 계획입니다.

</details>
